version: '3'
services:
  db:
    build: .
    image: mysql:latest
    environment:
      MYSQL_DATABASE: base
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
      MYSQL_ROOT_PASSWORD: foo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: 
      context: .
      dockerfile: app/dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
