# Utilisez une image de base contenant Python et Flask
FROM python:3.9

# Définissez le répertoire de travail dans l'image
WORKDIR /app

# Copiez les fichiers de votre application dans le répertoire de travail
COPY . /app

# Installez les dépendances de votre application
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Exposez le port que votre application Flask écoute
EXPOSE 5000

# Démarrez votre application Flask
CMD ["python", "app.py"]
